default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: abagiel
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: rubp_development

test:
  <<: *default
  database: rubp_test

production:
  <<: *default
  database: rubp_production
  username: task
  password: <%= ENV['TEST_TASK_DATABASE_PASSWORD'] %>